# Jekyll Resume Theme

# Site settings
title: Guillaume Vidal
email: guillaume@vidal.im
description: Site personnel de Guillaume Vidal
baseurl: "https://vidal.im"
#url: ""
name: Guillaume Vidal, PMP
job: Chef de Projet IT/Finance
location: Paris, France


github_username:  guillaumevidal/guillaumevidal.github.io
email_address: guillaume@vidal.im

# Build settings
markdown: kramdown
